# Dependabot configuration

version: 2

updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Must specify `/` for GitHub Actions in the `.github/workflows` directory
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday (Monday to Friday)
      interval: "daily"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every weekday (Monday to Friday)
    schedule:
      interval: "daily"
