name: test-sideboard
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [ '10', '12', '14' ]
    name: Node.js ${{ matrix.node }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Show application version
        run: ./bin/run --version
      - name: Show application help
        run: ./bin/run --help
      - name: Run tests
        run: npm test
