name: tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14', '15' ]
    name: Node.js ${{ matrix.node }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Cache Node.js modules
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Show application version
        run: ./bin/run --version
      - name: Show application help
        run: ./bin/run --help
      - name: Run tests
        run: npm test
